#!/bin/bash

ROOT="${0%/*}"
URL_LIST=$ROOT/URLS
TARGET_ERROR=$ROOT/logs/pingpong-error.log
TARGET_SUCCESS=$ROOT/logs/pingpong.log

echo "fetching urls from $URL_LIST"
echo "logs will be saved at $TARGET_SUCCESS and $TARGET_ERROR"

[[ $FOLLOW_LINKS == 0 ]] && FOLLOW="" || FOLLOW=" -L "
[[ $MAX_TIME -gt 0 ]] && TIMEOUT="$MAX_TIME" || TIMEOUT=10

if [[ ! -f $TARGET_SUCCESS ]]; then echo "[]" > $TARGET_SUCCESS; fi
if [[ ! -f $TARGET_ERROR ]]; then echo "[]" > $TARGET_ERROR; fi

logerror () {

	ERROR=$(echo "{\"date\":\"$(date +%F_%T)\",\"url\":\"$1\",\"error_code\":\"$2\"}" | jq -r -c '.')
	if [[ $? == 0 ]]; then

    LIST=$(cat $TARGET_ERROR | jq -r -c --argjson sample $ERROR '. |= . + [$sample] ')
    if [[ $? == 0 ]]; then
      echo $LIST > $TARGET_ERROR
    else
      echo $ERROR
      echo "[pingpong] jq couldnt append the error on the list"
    fi

  else
		echo "[pingpong] jq couldnt parse the error sample"
	fi
}

if [[ ! -f $URL_LIST ]]; then
	logerror "missing URL file" "e0"
	exit 1
fi

while read -r url; do

	URL=$(echo "$url" | awk '{print $1}')
	USER=$(echo "$url" | awk '{print $2}')

	[[ ! -z $USER ]] && LOGIN=" -u $USER" || LOGIN=""

	# only urls starting with http(s):// will be tested.
	if [[ $URL =~ ^https?:// ]]; then

	  printf "# fetching url $URL: "
		RESULT=$(curl $URL -w "@$ROOT/curl-parse-result" $FOLLOW $LOGIN --insecure \
			--max-time $TIMEOUT --compressed -I --silent -o /dev/null \
			-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36')
    EXIT_CODE=$?

		# check for last exit code
		if [[ $EXIT_CODE == 0 ]]; then

			# append date into sample object
			SAMPLE="$(echo $RESULT | jq -r -c --arg date "$(date +%F_%T)" '.date |= . + $date ' )"

			if [[ $? == 0 ]]; then

        LIST=$(cat $TARGET_SUCCESS | jq -r -c --argjson sample $SAMPLE '. |= . + [$sample] ' )
				if [[ ! $? == 0 ]]; then
					logerror "jq couldnt append the sample on the list" "e1"
        else
          echo $LIST > $TARGET_SUCCESS
          printf "ok\n"
				fi

			else
				logerror "jq couldnt append date or parse the given input" "e2"
			fi

		else
			logerror $URL "$EXIT_CODE"
			printf "error\n"
		fi

	fi

done < "$URL_LIST"

printf "# done"
exit 0
